### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by Canariiee00** [Xperidia/SuperPedobear#1]
Bonjour,

impossible de traduire en français... Comment faire ? 

2. Impossible d'utiliser le PointShop2 car le F3 est déjà pris dans votre config, comment faire 

Merci par avance

**Comment by VickyFrenzy** [comment]
Bonjour. 

Un système de langage n'a pas encore été implémenté.

Changez la touche de votre PointShop directement.

**Comment by Canariiee00** [comment]
Très bien, je sais pas encore comment changer la touche je cherche. Merci à vous, pour le langage dans combien de temps svp ?

**Comment by VickyFrenzy** [comment]
Je ne peux pas vraiment donner cette information pour le moment.
Super Pedobear n'est pas ma priorité.
Vous pouvez toujours faire un don en précisant de mettre le système de langage en priorité.

**Comment by Canariiee00** [comment]
J espère que cela ne sortira pas dans 3 ans.... il y as du potentiel c'est bien dommage...
