### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by Canariiee00** [Xperidia/SuperPedobear#2]
[ERROR] gamemodes/superpedobear/gamemode/semver.lua:1: unexpected symbol near '..'
1. unknown - gamemodes/superpedobear/gamemode/sh_utils.lua:6
2. include - [C]:-1
3. unknown - gamemodes/superpedobear/gamemode/shared.lua:8
4. include - [C]:-1
5. unknown - gamemodes/superpedobear/gamemode/init.lua:18
[ERROR] gamemodes/superpedobear/gamemode/semver.lua:1: unexpected symbol near '..'
1. unknown - gamemodes/superpedobear/gamemode/shared.lua:11
2. include - [C]:-1
3. unknown - gamemodes/superpedobear/gamemode/init.lua:18
[ERROR] gamemodes/superpedobear/gamemode/shared.lua:16: attempt to call local 'v' (a nil value)
1. unknown - gamemodes/superpedobear/gamemode/shared.lua:16
2. include - [C]:-1
3. unknown - gamemodes/superpedobear/gamemode/init.lua:18

J'ai modifié le fichier mais cela ne marche pas

**Comment by VickyFrenzy** [comment]
Cette erreur est connue si vous utilisez le .zip source de SuperPedobear.
Je vous recommande plutôt d'utiliser la version Workshop de Super Pedobear.
Guide: https://steamcommunity.com/workshop/filedetails/discussion/628449407/1696045708651107209/

Si vous souhaitez utiliser Super Pedobear sans le Steam Workshop:
Vous devez clone récursivement le repository avec les submodules Git et avoir les liens symboliques activés.
